### ISSUE TITLE
Links to RSMP Simulator

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp-nordic.github.io#10]
There are no links to download the RSMP Simulator or its documentation

**Comment by emiltin** [comment]
there's a link at https://rsmp-nordic.github.io/tools/#rsmp-simulator but it's incorrect pointing to the validator repo.

**Comment by otterdahl** [comment]
> there's a link at https://rsmp-nordic.github.io/tools/#rsmp-simulator but it's incorrect, pointing to the validator site.

Yes. I believe I just fixed that link. So, there is a link to the RSMP simulator repo, but the old site had a link to to download the executable installer and a link to the documentation. It is perhaps not absolutely necessary, but at least it would be good to point at the releases page https://github.com/rsmp-nordic/rsmp_simulator/releases

**Comment by emiltin** [comment]
maybe, or add download links to the readme in the repo? at https://github.com/rsmp-nordic/rsmp_simulator

**Comment by emiltin** [comment]
yeah good suggestion to link to the releases page on github

**Comment by otterdahl** [comment]
Added pull request https://github.com/rsmp-nordic/rsmp-nordic.github.io/pull/14

**Comment by emiltin** [comment]
done
