### ISSUE TITLE
Support for old links in requirements?

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp-nordic.github.io#11]
The RSMP specific requirements at the Swedish Transport Administration refers to https://rsmp-nordic.org/doks/.

Is it possible to temporarily add a sub directory (or automatic redirection) at doks/ which refers to https://rsmp-nordic.github.io/specification/ ? It takes about 3 months to update the requirements at the Swedish Transport Administration, including any links.

**Comment by emiltin** [comment]
until we move out new jekyll-based site to rsmp-nordic.org, we would have to edit the WordPress site. 
rather than spend time in that i suggest we move ahead and retire the wordpress site?

**Comment by otterdahl** [comment]
> until we move out new jekyll-based site to rsmp-nordic.org, we would have to edit the WordPress site. 
> rather than spend time in that i suggest we move ahead and retire the wordpress site?

Agree

**Comment by otterdahl** [comment]
What I meant with this issue is if we could add https://rsmp-nordic.org/doks/ (to point to https://rsmp-nordic.org/specification/) on the new website, just to maintain backward compatibility for a while until we have time to update the RSMP requirements at STA (Swedish Transport Administration).

**Comment by emiltin** [comment]
yes i understand. new new jekyll is not deployed to rsmp-nordic.org, so i will try to add a redirect  from docs/ to specifications/

**Comment by emiltin** [comment]
done. https://rsmp-nordic.org/doks/ now redirects to https://rsmp-nordic.org/specification/

**Comment by otterdahl** [comment]
> done. https://rsmp-nordic.org/doks/ now redirects to https://rsmp-nordic.org/specification/

Thanks!
